Integrate code from get_error.py
yashika51/AskFlow pull request #8
Opened 2020-11-22 14:08 UTC by yashika51

@Acrylami I have tried to integrate your code with mine.
Also as suggested the script now prints the answers as well. 
Can you please test if this works on your machine, the errors if any would be due to permissions or a file access problem?
No rush, whenever you're available, please let me know.

Meanwhile @Levy-Naibei, please check as well whenever possible. 

Thanks both!

2020-11-22 15:15 UTC, Acrylami commented
Hi Yashika I only see one changed file here and it doesn't look like it integrates it with any other files. I tried running cli.py and get_error.py and couldn't see any answers either. It looks like there might have been more changes you made that haven't been committed to this branch properly?

2020-11-22 16:42 UTC, yashika51 commented
@Acrylami oh I meant I combined/integrated code not files. I want you to check if `search_answers.py` is working fine. 
To test this, we have to pass `file_name` to the object of `class ask`. Then just call the function `get_answer()` with the help of object.

2020-11-22 16:43 UTC, yashika51 commented
For integrating files, we need to discuss it with @Levy-Naibei, how the output would be displayed in cli. The `search()` function would probably get the output from the `search_answers.py` and then it's up to @Levy-Naibei how to display it.

2020-11-22 19:41 UTC, Levy-Naibei requested changes
Hey @yashika51 ,
Where has "items" been declared?

2020-11-22 19:43 UTC, yashika51 commented
@Levy-Naibei `items` is a key in the JSON file we get from the API.

2020-11-22 19:44 UTC, Levy-Naibei commented
> @Levy-Naibei `items` is a key in the JSON file we get from the API.

2020-11-22 19:46 UTC, Levy-Naibei commented
> @Levy-Naibei `items` is a key in the JSON file we get from the API.

there is a key error in it, let me see that json file ..

2020-11-22 20:01 UTC, Levy-Naibei commented
> > @Levy-Naibei `items` is a key in the JSON file we get from the API.

@yashika51 , 
where is the link to that json file?

2020-11-22 20:04 UTC, yashika51 commented
@Levy-Naibei you have to read the API docs, the json file is returned when we run the query and it depends on what the error is. 
The error should not be with items or code in `search_answers.py`. Its returning the answers properly. You have to check `cli.py` for integration issues instead.

2020-11-22 20:08 UTC, Levy-Naibei commented
> @Levy-Naibei you have to read the API docs, the json file is returned when we run the query and it depends on what the error is.
> The error should not be with items or code in `search_answers.py`. Its returning the answers properly. You have to check `cli.py` for integration issues instead.

Ok

2020-11-22 20:44 UTC, Levy-Naibei commented
Hey @yashika51 
the import  and use of class `ask` is in cli.py is ok, the error we are getting should be in `items`. please check the data structure well in the API, may be `items` is a list of dictionary yet you are iterating it like a plain list.. plis check that first and let me know

2020-11-22 20:52 UTC, yashika51 commented
Levy running search_answers.py would tell you there's no error at all.
I have checked that part already. It's something with integration.
Let me know if search_answers.py gives any error. The instructions to test
is given in one of the previous PRs including screenshot. Thanks.

On Mon, Nov 23, 2020, 2:14 AM Levy Naibei <notifications@github.com> wrote:

> Hey @yashika51 <https://github.com/yashika51>
> the import and use of class ask is in cli.py is ok, the error we are
> getting should be in items. please check the data structure well in the
> API, may be items is a list of dictionary yet you are iterating it like a
> plain list.. plis check that first and let me know
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/yashika51/AskFlow/pull/8#issuecomment-731844316>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIKKYFX7NTLQE3CHDJJ2EJ3SRFZ3DANCNFSM4T6P4FUA>
> .
>

2020-11-22 20:56 UTC, Levy-Naibei commented
> Levy running search_answers.py would tell you there's no error at all. I have checked that part already. It's something with integration. Let me know if search_answers.py gives any error. The instructions to test is given in one of the previous PRs including screenshot. Thanks.
> […](#)
> On Mon, Nov 23, 2020, 2:14 AM Levy Naibei ***@***.***> wrote: Hey @yashika51 <https://github.com/yashika51> the import and use of class ask is in cli.py is ok, the error we are getting should be in items. please check the data structure well in the API, may be items is a list of dictionary yet you are iterating it like a plain list.. plis check that first and let me know — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub <[#8 (comment)](https://github.com/yashika51/AskFlow/pull/8#issuecomment-731844316)>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AIKKYFX7NTLQE3CHDJJ2EJ3SRFZ3DANCNFSM4T6P4FUA> .

2020-11-22 20:57 UTC, Levy-Naibei commented
which error message are you getting ?

2020-11-23 06:35 UTC, Levy-Naibei commented
@yashika51 , I am debugging using pdb and i can still see the error lies in data['items']  .. so just share that data i have a look at it

2020-11-23 09:05 UTC, Levy-Naibei commented
Hey @Acrylami and @yashika51, after long debugging, i have found out a fix that will make the CLI work.

Our error message(relevant info) needs to be cleaned up to `self.error_message='unsupported operand type(s) for int and str'`
if i hard code `unsupported operand type(s) for int and str'` in the class initialization method and run `python cli.py search "python error_test.py"` on the terminal, the application works well - it is able to fetch answers from stackoverflow.

currently it has a lot of irrelevant info `Relevant information for search: 
['Traceback (most recent call last)', '\n  File "error_test.py", line 4, in <module>\n    a = 10 + "b"\nTypeError', ' unsupported operand type(s) for +', " 'int' and 'str'"]`

so the `error_message` in `get_error.py` module needs to be cleansed to look like one above - only error message needed and remove info such as Traceback, File, Typerror etc

Hope this helps.. there you go

2020-11-23 11:35 UTC, Acrylami commented
Hi Levy thanks for this
What are the steps for reproducing this error?
The last time I ran the code is did not have all this irrelevant
information, as can be seen in a previous PR screenshot or in our discord
chat
It used to just say "type error", "unsupported operand....", "Int +
string..." In the list

On Mon, 23 Nov 2020, 09:06 Levy Naibei, <notifications@github.com> wrote:

> Hey @Acrylami <https://github.com/Acrylami> and @yashika51
> <https://github.com/yashika51>, after long debugging, i have found out a
> fix that will make the CLI work.
>
> Our error message(relevant info) needs to be cleaned up to self.error_message='unsupported
> operand type(s) for int and str'
> if i hard code unsupported operand type(s) for int and str' in the class
> initialization method and run python cli.py search "python error_test.py"
> on the terminal, the application works well - it is able to fetch answers
> from stackoverflow.
>
> currently it has a lot of irrelevant info Relevant information for
> search: ['Traceback (most recent call last)', '\n File "error_test.py",
> line 4, in <module>\n a = 10 + "b"\nTypeError', ' unsupported operand
> type(s) for +', " 'int' and 'str'"]
>
> so the error_message in get_error.py module needs to be cleansed to look
> like one above - only error message needed and remove info such as
> Traceback, File, Typerror etc
>
> Hope this helps.. there you go
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/yashika51/AskFlow/pull/8#issuecomment-732025928>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACPNBZDYB7NYXWX3R4BH2TLSRIQXZANCNFSM4T6P4FUA>
> .
>

2020-11-23 15:37 UTC, Acrylami commented on search_answers.py
> +from get_error import main
Should not be needed to import get_error anymore

2020-11-23 15:39 UTC, Acrylami approved these changes
Works for me.
Type "python cli.py search "python error_test.py"" to run
In future more work will be needed:

1. With the API to only return the most upvoted answer the the SO question- it seems it is returning all answers even bad answers? @yashika51 
2. With the user interface to display the answer in a readable way like issue #6 @Levy-Naibei

2020-11-23 15:39 UTC, Acrylami commented on cli.py
> +        print(answers[0])
I've changed it to only print the first answer to make it easier to look at

2020-11-24 16:01 UTC, merged